name: CI/CD Pipeline

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  # Job 1: Code Quality Checks
  quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: frontend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run frontend linting
      working-directory: frontend
      continue-on-error: true
      run: npm run lint || echo "Linting found issues (non-blocking)"

    - name: Check TypeScript types
      working-directory: frontend
      continue-on-error: true
      run: npx tsc --noEmit || echo "TypeScript check found issues (non-blocking)"

  # Job 2: Build Application
  build:
    runs-on: ubuntu-latest
    needs: quality
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: frontend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Create frontend environment file
      working-directory: frontend
      run: |
        cat > .env.local << EOF
        NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
        EOF

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/.next/
        retention-days: 7

  # Job 3: End-to-End Tests
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: examind_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install root dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Install backend dependencies
      working-directory: backend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Install frontend dependencies
      working-directory: frontend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Setup database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d examind_test -f backend/config/examindDB-schema.sql

    - name: Create backend environment file
      run: |
        cd backend
        cat > .env << EOF
        DB_USER=postgres
        DB_HOST=localhost
        DB_DATABASE=examind_test
        DB_PASSWORD=postgres
        DB_PORT=5432
        JWT_SECRET=test_jwt_secret_key_for_ci_cd_pipeline
        NODE_ENV=test
        EOF

    - name: Create frontend environment file
      run: |
        cd frontend
        cat > .env.local << EOF
        NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
        EOF

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Start backend server
      working-directory: backend
      run: |
        nohup npm start > backend.log 2>&1 &
        echo $! > backend.pid
        
    - name: Wait for backend
      run: |
        echo "Waiting for backend to start..."
        for i in {1..30}; do
          if curl -f http://localhost:8080/api/health 2>/dev/null; then
            echo "Backend is ready!"
            break
          fi
          echo "Attempt $i: Backend not ready yet..."
          sleep 2
        done
        
    - name: Start frontend server
      working-directory: frontend
      run: |
        nohup npm start > frontend.log 2>&1 &
        echo $! > frontend.pid
        
    - name: Wait for frontend
      run: |
        echo "Waiting for frontend to start..."
        for i in {1..30}; do
          if curl -f http://localhost:3000 2>/dev/null; then
            echo "Frontend is ready!"
            break
          fi
          echo "Attempt $i: Frontend not ready yet..."
          sleep 2
        done

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://localhost:3000

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-results/
        retention-days: 30

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Display logs on failure
      if: ${{ failure() }}
      run: |
        echo "=== Backend Logs ==="
        cat backend/backend.log || echo "No backend logs found"
        echo ""
        echo "=== Frontend Logs ==="
        cat frontend/frontend.log || echo "No frontend logs found"
        
    - name: Cleanup processes
      if: ${{ always() }}
      run: |
        if [ -f backend/backend.pid ]; then
          kill $(cat backend/backend.pid) || true
        fi
        if [ -f frontend/frontend.pid ]; then
          kill $(cat frontend/frontend.pid) || true
        fi

    - name: Generate test summary
      if: ${{ always() }}
      run: |
        echo "## 🧪 Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Results**: [Download](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)" >> $GITHUB_STEP_SUMMARY
        echo "- **Playwright Report**: [View Report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Coverage:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ User Authentication & Registration" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Dashboard & User Profile" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Quiz Management & Taking" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Resource Management" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Discussion Forums" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Gamification & Badges" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Teacher Dashboard" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Admin Dashboard" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Subject Management" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Edge Cases & Error Handling" >> $GITHUB_STEP_SUMMARY

    - name: Notify on failure
      if: ${{ failure() }}
      run: |
        echo "❌ Tests failed on branch ${{ github.ref_name }}"
        echo "Check the test results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    # Optional: Add Slack notification here if you have Slack webhook
    # - name: Slack Notification
    #   if: ${{ always() }}
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #     SLACK_MESSAGE: "Test Results: ${{ job.status }} - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  # Job 4: Security Scan (Optional)
  security:
    runs-on: ubuntu-latest
    needs: quality
    continue-on-error: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: frontend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run npm audit
      working-directory: frontend
      continue-on-error: true
      run: npm audit --audit-level moderate || echo "Frontend audit found issues (non-blocking)"

    - name: Install backend dependencies
      working-directory: backend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run backend npm audit
      working-directory: backend
      continue-on-error: true
      run: npm audit --audit-level moderate || echo "Backend audit found issues (non-blocking)"